CREATE TABLE datos_personales (id_persona int(10) NOT NULL AUTO_INCREMENT, nombre varchar(75) NOT NULL, apellidoP varchar(75) NOT NULL, apellidoM varchar(75) NOT NULL, fecha_nacimiento date NOT NULL, sexo int(10) NOT NULL, domicilio varchar(255) NOT NULL, telefono bigint(10) NOT NULL, PRIMARY KEY (id_persona));
CREATE TABLE usuarios (id_usuario int(10) NOT NULL AUTO_INCREMENT, id_persona int(10) NOT NULL, contrasena varchar(25) NOT NULL, id_rol int(10) NOT NULL, PRIMARY KEY (id_usuario));
CREATE TABLE expedientes (id_expediente int(10) NOT NULL AUTO_INCREMENT, id_persona int(10) NOT NULL, PRIMARY KEY (id_expediente));
CREATE TABLE padecimientos (id_padecimiento int(10) NOT NULL AUTO_INCREMENT, nombre varchar(255) NOT NULL, descripcion varchar(255) NOT NULL, PRIMARY KEY (id_padecimiento));
CREATE TABLE pacientes_padecimientos (id_expediente int(10) NOT NULL, id_padecimiento int(10) NOT NULL, PRIMARY KEY (id_expediente, id_padecimiento));
CREATE TABLE ambulancias (id_ambulancia int(10) NOT NULL AUTO_INCREMENT, numero int(10) NOT NULL, placa varchar(15) NOT NULL, PRIMARY KEY (id_ambulancia));
CREATE TABLE operador (id_ambulancia int(10) NOT NULL, id_usuario int(10) NOT NULL, PRIMARY KEY (id_ambulancia, id_usuario));
CREATE TABLE historial (id_historial int(10) NOT NULL AUTO_INCREMENT, id_expediente int(10) NOT NULL, observaciones varchar(255) NOT NULL, fecha_atencion timestamp NOT NULL, id_estado int(10) NOT NULL, PRIMARY KEY (id_historial));
CREATE TABLE rol (id_rol int(10) NOT NULL AUTO_INCREMENT, nombre_rol varchar(20) NOT NULL, PRIMARY KEY (id_rol));
CREATE TABLE sexo (id_sexo int(10) NOT NULL AUTO_INCREMENT, nombre_sexo varchar(20) NOT NULL, PRIMARY KEY (id_sexo));
CREATE TABLE `pre-hospitalario` (id_prehospitalario int(10) NOT NULL AUTO_INCREMENT, fecha date NOT NULL, hora_salida time NOT NULL, hora_llegada time NOT NULL, ordeno varchar(255) NOT NULL, ubicacion varchar(255) NOT NULL, motivo varchar(255) NOT NULL, translado varchar(255) NOT NULL, lugar varchar(255) NOT NULL, id_ambulancia int(10) NOT NULL, id_operador int(10) NOT NULL, id_tmu int(10) NOT NULL, id_medico int(10) NOT NULL, id_camillero int(10) NOT NULL, PRIMARY KEY (id_prehospitalario));
CREATE TABLE `historial-prehospitalario` (id_historial int(10) NOT NULL, id_prehospitalario int(10) NOT NULL, PRIMARY KEY (id_historial, id_prehospitalario));
CREATE TABLE estado (id_estado int(10) NOT NULL AUTO_INCREMENT, sit_estado varchar(60) NOT NULL, PRIMARY KEY (id_estado));
ALTER TABLE usuarios ADD CONSTRAINT FKusuarios801063 FOREIGN KEY (id_persona) REFERENCES datos_personales (id_persona);
ALTER TABLE operador ADD CONSTRAINT FKoperador990243 FOREIGN KEY (id_ambulancia) REFERENCES ambulancias (id_ambulancia);
ALTER TABLE pacientes_padecimientos ADD CONSTRAINT FKpacientes_599457 FOREIGN KEY (id_padecimiento) REFERENCES padecimientos (id_padecimiento);
ALTER TABLE expedientes ADD CONSTRAINT FKexpediente674020 FOREIGN KEY (id_persona) REFERENCES datos_personales (id_persona);
ALTER TABLE usuarios ADD CONSTRAINT FKusuarios640334 FOREIGN KEY (id_rol) REFERENCES rol (id_rol);
ALTER TABLE datos_personales ADD CONSTRAINT FKdatos_pers459564 FOREIGN KEY (sexo) REFERENCES sexo (id_sexo);
ALTER TABLE pacientes_padecimientos ADD CONSTRAINT FKpacientes_282770 FOREIGN KEY (id_expediente) REFERENCES expedientes (id_expediente);
ALTER TABLE historial ADD CONSTRAINT FKhistorial698988 FOREIGN KEY (id_expediente) REFERENCES expedientes (id_expediente);
ALTER TABLE `historial-prehospitalario` ADD CONSTRAINT `FKhistorial-339505` FOREIGN KEY (id_historial) REFERENCES historial (id_historial);
ALTER TABLE `historial-prehospitalario` ADD CONSTRAINT `FKhistorial-279469` FOREIGN KEY (id_prehospitalario) REFERENCES `pre-hospitalario` (id_prehospitalario);
ALTER TABLE operador ADD CONSTRAINT FKoperador201421 FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);
ALTER TABLE `pre-hospitalario` ADD CONSTRAINT `FKpre-hospit21767` FOREIGN KEY (id_tmu) REFERENCES usuarios (id_usuario);
ALTER TABLE `pre-hospitalario` ADD CONSTRAINT `FKpre-hospit755522` FOREIGN KEY (id_medico) REFERENCES usuarios (id_usuario);
ALTER TABLE `pre-hospitalario` ADD CONSTRAINT `FKpre-hospit733432` FOREIGN KEY (id_camillero) REFERENCES usuarios (id_usuario);
ALTER TABLE `pre-hospitalario` ADD CONSTRAINT `FKpre-hospit372990` FOREIGN KEY (id_ambulancia, id_operador) REFERENCES operador (id_ambulancia, id_usuario);
ALTER TABLE historial ADD CONSTRAINT FKhistorial135051 FOREIGN KEY (id_estado) REFERENCES estado (id_estado);
